blank_issues_enabled: false
contact_links:
  - name: IPZ Theme Translations @ Transifex
    url: https://www.transifex.com/code-for-croatia/imamo-pravo-znati/
    about: Please use Transifex to fix text issues in the ImamoPravoZnati theme.
  - name: IPZ Middleware Issues
    url: https://github.com/codeforcroatia/imamopravoznati/issues
    about: Any non-theme issue should be raised and tracked in 'imamopravoznati' middleware repository.
