PublicBodyCategories.add(:it, [
        "Miscellaneous",
            [ "", "", "" ],
            [ "servizio", "Servizio", "servizio" ],
            [ "ordini_e_collegi_professionali", "Ordini e collegi professionali", "ordini e collegi professionali" ],
            [ "osservatorio", "Osservatorio", "osservatorio" ],
            [ "circoli_didattici", "Circoli didattici", "circoli didattici" ],
            [ "struttura", "Struttura", "struttura" ],
            [ "commissariato", "Commissariato", "commissariato" ],
            [ "agenzia", "Agenzia", "agenzia" ],
            [ "organi_costituzionali_e_di_rilievo_costituzionale", "Organi Costituzionali e di rilievo Costituzionale", "organi costituzionali e di rilievo costituzionale" ],
            [ "tribunale", "Tribunale", "tribunale" ],
            [ "istituti_di_istruzione_superiore", "Istituti di istruzione superiore", "istituti di istruzione superiore" ],
            [ "area", "Area", "area" ],
            [ "enti_e_aziende_ospedaliere", "Enti e Aziende Ospedaliere", "enti e aziende ospedaliere" ],
            [ "archivio", "Archivio", "archivio" ],
            [ "segretariato_generale", "Segretariato Generale", "segretariato generale" ],
            [ "segreteria", "Segreteria", "segreteria" ],
            [ "dipartimento", "Dipartimento", "dipartimento" ],
            [ "provveditorato", "Provveditorato", "provveditorato" ],
            [ "aziende_sanitarie_locali", "Aziende Sanitarie Locali", "aziende sanitarie locali" ],
            [ "biblioteca", "Biblioteca", "biblioteca" ],
            [ "enti_e_agenzie_regionali", "Enti e agenzie regionali", "enti e agenzie regionali" ],
            [ "camere_di_commercio", "Camere di Commercio", "camere di commercio" ],
            [ "circoscrizione", "Circoscrizione", "circoscrizione" ],
            [ "corte_di_appello", "Corte di Appello", "corte di appello" ],
            [ "comitato", "Comitato", "comitato" ],
            [ "comunita_montane", "Comunità montane", "comunità montane" ],
            [ "distretto", "Distretto", "distretto" ],
            [ "province", "Province", "province" ],
            [ "ministeri", "Ministeri", "ministeri" ],
            [ "sezione", "Sezione", "sezione" ],
            [ "societa_partecipate", "Società partecipate", "società partecipate" ],
            [ "punto_contatto_cittadino", "Punto Contatto Cittadino", "punto contatto cittadino" ],
            [ "istituto", "Istituto", "istituto" ],
            [ "comuni", "Comuni", "comuni" ],
            [ "direzione", "Direzione", "direzione" ],
            [ "centro", "Centro", "centro" ],
            [ "enti_e_istituti_di_previdenza", "Enti e Istituti di previdenza", "enti e istituti di previdenza" ],
            [ "sede", "Sede", "sede" ],
            [ "istituti_di_istruzione", "Istituti di Istruzione", "istituti di istruzione" ],
            [ "settore", "Settore", "settore" ],
            [ "istituti_di_pena_e_rieducazione", "Istituti di Pena e Rieducazione", "istituti di pena e rieducazione" ],
            [ "unita_organizzativa", "Unità Organizzativa", "unità organizzativa" ],
            [ "procura", "Procura", "procura" ],
            [ "ispettorato", "Ispettorato", "ispettorato" ],
            [ "sportello_multifunzione", "Sportello Multifunzione", "sportello multifunzione" ],
            [ "gabinetto", "Gabinetto", "gabinetto" ],
            [ "enti_e_istituti_di_ricerca", "Enti e istituti di ricerca", "enti e istituti di ricerca" ],
            [ "agenzie", "Agenzie", "agenzie" ],
            [ "istituzioni_dellunione_europea", "Istituzioni dell'Unione Europea", "istituzioni dell'unione europea" ],
            [ "associazioni_di_categoria", "Associazioni di categoria", "associazioni di categoria" ],
            [ "centro_per_limpiego", "Centro per l'Impiego", "centro per l'impiego" ],
            [ "autorita_indipendenti", "Autorità indipendenti", "autorità indipendenti" ],
            [ "universita", "Università", "università" ],
            [ "comando", "Comando", "comando" ],
            [ "ufficio_stampa", "Ufficio Stampa", "ufficio stampa" ],
            [ "consorzi_e_unioni_territoriali", "Consorzi e unioni territoriali", "consorzi e unioni territoriali" ],
            [ "nucleo", "Nucleo", "nucleo" ],
            [ "regioni", "Regioni", "regioni" ],
            [ "ufficio", "Ufficio", "ufficio" ],
            [ "altri_enti_pubblici", "Altri enti pubblici", "altri enti pubblici" ],
    ]
)